apiVersion: apps/v1
kind: Deployment
metadata:
  name: twootservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twootservice
  template:
    metadata:
      labels:
        app: twootservice
    spec:
      containers:
        - name: twootservice
          image: ninoverhaegh/twootservice:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
